name: .NET Build and Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Replace with the version of .NET you need

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the application
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Test
        run: dotnet test --no-build --configuration Release
        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs after the "build" job is successful

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Set up in GitHub Secrets

    - name: Publish to Azure Web App
      run: |
        dotnet publish -c Release -o ./publish
        az webapp deploy --resource-group <RESOURCE_GROUP> --name <WEB_APP_NAME> --src-path ./publish

