name: Run Discord Bot

on:
  push:
    branches:
      - main 
  workflow_dispatch: 
jobs:
  build-and-run:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        env:
          DOTNET_INSTALL_DIR: "/home/romoboss/Documents/.NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run the bot
        run: dotnet run --project DrobbiBot.csproj > bot.log
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
